### PR TITLE
Fixed #10: Added support for process name in MacOS Activity Monitor

### LINKED ISSUE #10: setproctitle doesn't change "Process Name" in Activity Monitor.app on OS X
Originally submitted by **danlarkinwhat** as **issue 10**:

On OS X, setproctitle affects the output from /bin/ps, but not the &quot;Process Name&quot; in Activity Monitor.app.

Here's an informative thread discussing this issue on the node.js mailing list:
http://groups.google.com/group/nodejs/browse_thread/thread/cfe27a56d1875b52

The penultimate post on that thread includes a patch that supposedly fixes the problem -- perhaps you could think about including something similar.

### PR DESCRIPTION
**Pull request by gershnik**
Idea is borrowed from libuv (used by node.js)
See https://github.com/libuv/libuv/blob/v1.x/src/unix/darwin-proctitle.c
Implementation rewritten from scratch, fixing various libuv bugs among other things

### CODE REVIEW

**Comment by dvarrazzo** [comment]
Hello, thank you for this.

Is it possible to have tests for the feature?

**Comment by gershnik** [comment]
Good point. Test added.

**Comment by dvarrazzo** [comment]
We need an entry for the HISTORY file.

Do we need to add any note to the docs too? What do you propose?

I assume this should be released in a version 1.3.0 as it's a new feature.

**Comment by gershnik** [comment]
Yeah 1.3 sounds right from semantic versioning POV. Incidentally I have another Mac fix ready for the issues with Apple's Python not exporting Py_GetArgcArgv as well as change that adds type hints (this one I am less sure about). If approved, all can go in 1.3

Re docs looks like right now the only mention of where the title is expected to appear is in:
> The ``setproctitle`` module allows a process to change its title (as displayed
> by system tools such as ``ps`` and ``top``).

It can be changed to:

> The ``setproctitle`` module allows a process to change its title (as displayed
> by system tools such as ``ps``, ``top`` or MacOS Activity Monitor).

For HISTORY I assume something like

```
- Added support for displaying title as process name in MacOS Activity Monitor  (issue #10).
```

would work. What is your process for updating it? Do you do it before release or each change adds its own entry?

**Comment by dvarrazzo** [comment]
The docs/history changes are ok for me: please add them in this branch. I will bump up the version number on the master branch.

I am also  interested in the other fixes you have for macOS, as it's a platform I don't use and it's hard for me to test 

About providing type hints - I was thinking too about providing them in 1.3 - it might either be a pyi file iirc (psycopg 3's psycopg_c package is a good example) but we might also make the c module internal, and provide a python stub, which would be type hinted and could act as no-op fallback if compiling the c module fails.

**Comment by gershnik** [comment]
Done. I'll send the PR for the other Mac bug shortly.

With regards to type hints I added a stubs package which seems to work well with PyCharm and VSCode. No idea if this is the "right" approach - there seems to be no information online on how to do this for a native extension (or my Google-foo is lacking). I'll take a look at psycopg_c. You can see what I did at [gershnik:type-annotations](https://github.com/gershnik/py-setproctitle/commit/4945f9d385f4dfb62b8a7da75318e92a00cade10)

**Pull request merged**
